---
title: "List of Publications"
---


   
## 2022

**Inferring disease architecture and predictive ability with LDpred2-auto.**   
*F Privé, C Albiñana, B Pasaniuc, BJ Vilhjálmsson. *  
https://doi.org/10.1101/2022.10.10.511629


**Publicly Available Privacy-preserving Benchmarks for Polygenic Prediction.**     
*MJ Witteveen, EM Pedersen, J Meijsen, MR Andersen, F Privé, D Speed, and BJ Vilhjálmsson.*   
https://doi.org/10.1101/2022.10.10.510645


**Identifying and correcting for misspecifications in GWAS summary statistics and polygenic scores.**     
*F Privé, J Arbel, H Aschard, BJ Vilhjálmsson.*   
https://doi.org/10.1016/j.xhgg.2022.100136


**Accounting for age of onset and family history improves power in genome-wide association studies.**     
*EM Pedersen, E Agerbo, O Plana-Ripoll, J Grove, JW Dreier, KL Musliner, M Bækvad-Hansen, G Athanasiadis, A Schork, D Demontis, J Bybjerg-Grauholm, DM Hougaard, T Werge, M Nordentoft, O Mors, S Dalsgaard, J Christensen,  AD Børglum, PB Mortensen, JJ McGrath, F Privé, BJ Vilhjálmsson.*   
https://doi.org/10.1016/j.ajhg.2022.01.009


**Harnessing the power of population cohorts to study the relationship between endocrine-metabolic disorders and depression.**   
*A Jespersen, Z Yilmaz, BJ Vilhjálmsson.*   
***in press***


**Interplay of ADHD Polygenic Liability With Birth-Related, Somatic, and Psychosocial Factors in ADHD: A Nationwide Study.**      
*I Brikell, T Wimberley, C Albinana, BJ Vilhjálmsson, E Agerbo, AD Borglum, D Demontis, AJ Schork, S LaBianca, T Werge, DM Hougaard, M Nordentoft, O Mors, PB Mortensen, LV Petersen, S Dalsgaard.*   
https://doi.org/10.1176/appi.ajp.21111105


**Multi-PGS enhances polygenic prediction: weighting 937 polygenic scores.**        
*C Albiñana, Z Zhu, AJ Schork, A Ingason, H Aschard, I Brikell, CM Bulik, LV Petersen, E Agerbo, J Grove, M Nordentoft, DM Hougaard, T Werge, AD Børglum, PB Mortensen, JJ McGrath, BM Neale,  F Privé, BJ Vilhjálmsson.*   
https://doi.org/10.1101/2022.09.14.22279940


**ADuLT: An efficient and robust time-to-event GWAS.**     
*EM Pedersen, E Agerbo, O Plana-Ripoll, J Steinbach, MD Krebs, DM Hougaard, T Werge, M Nordentoft, A Børglum,  KL Musliner, A Ganna, AJ Schork, PB Mortensen,  JJ McGrath,  F Privé, BJ Vilhjálmsson.*    
https://doi.org/10.1101/2022.08.11.22278618


**Deep integrative models for large-scale human genomics.**     
*AI Sigurdsson,  D Westergaard, O Winther, O Lund, S Brunak, BJ Vilhjálmsson, S Rasmussen.*   
https://doi.org/10.1101/2021.06.11.447883


**Identification of 64 new risk loci for major depression, refinement of the genetic architecture and risk prediction of recurrence and comorbidities.**     
*TD Als, M Kurki, J Grove, G Voloudakis, K Therrien, J Naamanka, TT Nielsen, K Veerapen, D Levey, J Bendl, J Bybjerg-Grauholm, B Zheng, D Demontis, A Rosengren, G Athanasiadis, M Bækved-Hansen, P Qvist, B Walters, H Stefánsson, K Musliner, V Manikandan, L Farajzadeh, J Thirstrup, S Dinesen, BJ Vilhjálmsson, JJ McGrath, M Mattheisen, S Meier, iPSYCH-Broad Consortium, E Agerbo, K Stefánsson, M Nordentoft, T Werge, DM Hougaard, PB Mortensen, M Stein, J Gelernter, I Hovatta, P Roussos, MJ Daly, O Mors, A Palotie, and AD Børglum.*   
https://doi.org/10.1101/2022.08.24.22279149 


**Polygenic scoring accuracy varies across the genetic ancestry continuum in all human populations.**     
*Y Ding, K Hou, Z Xu, A Pimplaskar, E Petter, K Boulier, F Privé, BJ Vilhjálmsson, LO Loohuis, B Pasaniuc.*    
https://doi.org/10.1101/2022.09.28.509988


**Genetic correlates of vitamin D-binding protein and 25 hydroxyvitamin D in neonatal dried blood spots.**     
*C Albiñana, Z Zhu, N Borbye-Lorenzen, S Grundvad Boelt, AS Cohen, K Skogstrand, NR Wray, JA Revez, F Privé, LV Petersen, C Bulik, O Plana-Ripoll, KL Musliner, E Agerbo, A Børglum, DM Hougaard, M Nordentoft, T Werge, PB Mortensen, BJ Vilhjálmsson, JJ McGrath.*   
https://doi.org/10.1101/2022.06.08.22276164


**Discriminating bipolar disorder type I and II using polygenic risk scores for bipolar disorder, schizophrenia and major depression.**     
*J-CPG Debost, E Agerbo, BJ Vilhjálmsson, PB Mortensen, T Munk-Olsen, LV Petersen.*    
***in press***


**Polygenic risk and episode polarity among individuals with bipolar disorder.**     
*S Hasseris, C Albiñana, BJ Vilhjálmsson, PB Mortensen, SD Østergaard, KL Musliner.*    
***in press***


**Genetic liability to posttraumatic stress disorder and its association with postpartum depression.**     
*KB Madsen, X Liu, C Albiñana, BJ Vilhjálmsson, PB Mortensen, DM Hougaard, M Nordentoft, T Werge, O Mors, AD Børglum, T Munk-Olsen.*   
***in press***


**Portability of 245 polygenic scores when derived and applied in the same cohort.**     
*F Privé, H Aschard, S Carmi, L Folkersen, C Hoggart, P O’Reilly, BJ Vilhjálmsson.*   
https://doi.org/10.1016/j.ajhg.2021.11.008


**Large uncertainty in individual PRS estimation impacts PRS-based risk stratification.**     
<<<<<<< HEAD
*Y Ding, K Hou, K Burch, S Lapinska, F Privé, BJ Vilhjálmsson, S Sankararaman, B Pasaniuc.*    
=======
*Y Ding, K Hou, K Burch, S Lapinska, F Privé, BJ Vilhjálmsson, S Sankararaman, B Pasaniuc.* 
>>>>>>> 9f6a0f264acf51d11b17707daa2adf3de8e8e505
https://doi.org/10.1101/2020.11.30.403188


**Correcting for contamination with bovine serum albumin-associated vitamin D metabolites in protein extracts from neonatal dried blood spots.**     
*SG Boelt, O Plana-Ripoll, C Albiñana, BJ Vilhjálmsson, JJ  McGrath, AS Cohen.*   
https://doi.org/10.1186/s13104-022-06077-1


**Early life injuries and the development of attention-deficit hyperactivity disorder. **     
*T Wimberley, I Brikell, EM Pedersen, E Agerbo, BJ Vilhjálmsson, C Albiñana, F Privé, A Thapar, K Langley, L Riglin, M Simonsen, HS Nielsen, AD Børglum, M Nordentoft, PB Mortensen, S Dalsgaard.*   
https://doi.org/10.4088/JCP.21m14033


**Genome-wide association study of febrile seizures identifies seven new loci implicating fever response and neuronal excitability genes.  **   
*L Skotte, J Fadista, J Bybjerg-Grauholm, V Appadurai, MS Hildebrand, TF Hansen, K Banasik, J Grove, CA Climent, F Geller, CF Bjurström, BJ Vilhjálmsson, M Coleman, JA Damiano, R Burgess, IE Scheffer, OBV Pedersen, C Erikstrup, D Westergaard, KR Nielsen, E Sørensen, MT Bruun, X Liu, H Hjalgrim, TH Pers, PB Mortensen, O Mors, M Nordentoft, JW Dreier, A Børglum, J Christensen, DM Hougaard, A Buil, A Hviid, M Melbye, H Ullum, SF Berkovic, T Werge, B Feenstra.*   
https://doi.org/10.1093/brain/awab260


**Using the UK Biobank as a global reference of worldwide populations: application to measuring ancestry diversity from GWAS summary statistics.  **   
*F Privé*   
https://doi.org/10.1093/bioinformatics/btac348


**Pervasive Downward Bias in Estimates of Liability-Scale Heritability in Genome-wide Association Study Meta-analysis: A Simple Solution.  **   
*A D Grotzinger, J de la Fuente, F Privé, M G. Nivard, E M Tucker-Drob*   
https://doi.org/10.1016/j.biopsych.2022.05.029


**Optimal linkage disequilibrium splitting.  **   
*F Privé*   
https://doi.org/10.1093/bioinformatics/btab519



   
## 2021

**Investigating the shared genetic architecture between multiple sclerosis and inflammatory bowel diseases. **    
*Y Yang, H Musco, S Simpson-Yap, Z Zhu, Y Wang, X Lin, J Zhang, B Taylor, J Gratten, Y Zhou*   
https://doi.org/10.1038/s41467-021-25768



**Finding hidden treasures in summary statistics from genome-wide association studies.**     
*F Privé, Z Zhu, BJ Vilhjálmsson. *   
https://doi.org/10.1038/s41588-021-00824-z


**Improved genetic prediction of complex traits from individual-level data or summary statistics.  **   
*Q Zhang, F Privé, BJ Vilhjálmsson, D Speed.*   
https://doi.org/10.1038/s41467-021-24485-y 


**Estimating the effective sample size in association studies of quantitative traits.  **   
*A. Ziyatdinov, J Kim, D Prokopenko, F Privé, F Laporte, P Loh, P Kraft, H Aschard*   
https://doi.org/10.1093/g3journal/jkab057


**Leveraging both individual-level genetic data and GWAS summary statistics increases polygenic prediction. **    
*C Albiñana, J Grove, JJ McGrath, E Agerbo, NR Wray, CM Bulik, M Nordentoft, DM Hougaard, T Werge, AD Børglum, PB Mortensen, F Privé, BJ Vilhjálmsson*    
https://doi.org/10.1016/j.ajhg.2021.04.014



**Evaluating the interrelations between individual genetic liability and psychiatric family history in risk for autism. **    
*D Schendel, TM Laursen, C Albiñana, BJ Vilhjalmsson, C Ladd-Acosta, MD Fallin, K Benke, B Lee, J Grove, A Kalkbrenner, L Ejlskov, D Hougaard, J Bybjerg-Grauholm, M Bækvad-Hansen, AD Børglum, T Werge, M Nordentoft, PB Mortensen, E Agerbo.*   
https://doi.org/10.1002/aur.2629


**Multitrait GWAS to connect disease variants and biological mechanisms.  **   
*H Julienne, V Laville, ZR McCaw, Z He, V Guillemot, C Lasry, A Ziyatdinov, C Nerin, A Vaysse, P Lechat, H Ménager, W Le Goff, M-P Dube, P Kraft, I Ionita-Laza, BJ Vilhjálmsson, H Aschard.*   
https://doi.org/10.1371/journal.pgen.1009713


**Anorexia nervosa and inflammatory bowel diseases - diagnostic and genetic associations. **    
*JT Larsen, Z Yilmaz, BJ Vilhjálmsson, LM Thornton, ME Benros, KL Musliner, T Werge, DM Hougaard, PB Mortensen, CM Bulik, LV Petersen.*   
https://doi.org/10.1002/jcv2.12036


**Genetic, Clinical, and Sociodemographic Factors Associated With Stimulant Treatment Outcomes in ADHD.  **   
*I Brikell, T Wimberley, C Albiñana, EM Pedersen, BJ Vilhjálmsson, E Agerbo, D Demontis, AD Børglum, A Schork, S LaBianca, T Werge, M Nordentoft, O Mors, D Hougaard, A Thapar, PB Mortensen, S Dalsgaard.*   
https://doi.org/10.1176/appi.ajp.2020.20121686


**Developmental exposure to vitamin D deficiency and subsequent risk of schizophrenia.**     
*C Albiñana, SG Boelt, AS Cohen, Z Zhu, KL Musliner, BJ Vilhjálmsson, JJ McGrath.*   
https://doi.org/10.1016/j.schres.2021.06.004


**A polygenic risk score improves risk stratification of obstructive coronary artery disease beyond clinical risk factors in patients with stable chest symptoms.  **   
*MK Christiansen, S Winther, L Nissen, BJ Vilhjálmsson, L Frost, JK Johansen, PL Møller, SE Schmidt, J Westra, NR Holm, HK Jensen, EH Christiansen, DF Guðbjartsson, H Hólm, K Stefánsson, HE Bøtker, M Bøttcher, M Nyegaard.*   
https://doi.org/10.1161/CIRCGEN.120.003298


**Polygenic Liability and Recurrence of Depression in Patients With First-Onset Depression Treated in Hospital-Based Settings.**     
*KL Musliner, KK Andersen, E Agerbo, C Albiñana, BJ Vilhjálmsson, VM Rajagopal, J Bybjerg-Grauholm, M Bækved-Hansen, CB Pedersen, MG Pedersen, T Munk-Olsen, ME Benros, T Als, J Grove, T Werge, AD Børglum, DM Hougaard, O Mors, M Nordentoft, PB Mortensen, NP Suppli.*   
https://doi.org/10.1001/jamapsychiatry.2021.0701


**Polygenic liability, stressful life events and risk for developing severe depression in early life: A nationwide register-based case-cohort study.  **   
*KL Musliner, E Agerbo, BJ Vilhjálmsson, C Albiñana, TD Als, SD Østergaard, PB Mortensen.*   
https://doi.org/10.1017/s0033291721001410


**Risk of Major Depression, Polygenic Risk Score for Depression, Parental Socio-Economic Status and History of Mental Disorders: A Danish Population-Based Study.  **   
*E Agerbo, BB Trabjerg, AD Børglum, AJ Schork, BJ Vilhjálmsson, CB Pedersen, C Hakulinen, C Albiñana, DM Hougaard, J Grove, JJ McGrath, J Bybjerg-Grauholm, O Mors, O Plana-Ripoll, T Werge, NR Wray, PB Mortensen, KL Musliner.*   
https://doi.org/10.1001/jamapsychiatry.2020.4172


   
## 2020

**LDpred2 : better, faster, stronger.  **   
*F Privé, J Arbel, BJ Vilhjálmsson.*   
https://doi.org/10.1093/bioinformatics/btaa1029


**Polygenic risk score, psychosocial environment and the risk of attention-deficit/hyperactivity disorder.**     
*SD Østergaard, BB Trabjerg, TD Als, C Albiñana Climent, F Privé, BJ Vilhjálmsson, M Bækvad-Hansen, J Bybjerg-Grauholm, DM Hougaard, M Nordentoft, T Werge, D Demontis, PB Mortensen, AD Børglum, O Mors, E Agerbo.*   
https://doi.org/10.1038/s41398-020-01019-6


**Efficient toolkit implementing best practices for principal component analysis of population genetic data.**     
*F Privé, K Luu, MG Blum, JJ McGrath, BJ Vilhjálmsson. *   
https://doi.org/10.1093/bioinformatics/btaa520


**Performing highly efficient genome scans for local adaptation with R package pcadapt version 4.  **   
*F Privé, K Luu, BJ Vilhjálmsson, MGB Blum.*     
https://doi.org/10.1093/molbev/msaa053


**Polygenic Risk Score, Psychosocial Environment and the Risk of ADHD. **     
https://doi.org/10.1038/s41398-020-01019-6


**Families, health-registers, and biobanks – making the unmeasurable measurable. **     
*C Albiñana, BJ Vilhjálmsson, JJ McGrath.*   
https://doi.org/10.1016/j.biopsych.2020.06.025


**Nature and prevalence of combinations of mental disorders and their association with excess mortality in a population-based cohort study.   **   
*O Plana-Ripoll, KL Musliner, S Dalsgaard, NC Momen, N Weye, MK Christensen, E Agerbo, KM Iburg, TM Laursen, PB Mortensen, CB Pedersen, LV Petersen, DF Santomauro, BJ Vilhjálmsson, HA Whiteford, JJ McGrath.*   
https://doi.org/10.1002/wps.20802


**Genetic liability to major depression and risk of childhood asthma. **     
*X Liu, T Munk-Olsen, C Albiñana, BJ Vilhjálmsson, E Pedersen, V Schlünssen, M Bækvad-Hansen, J Bybjerg-Grauholm, M Nordentoft, A Børglum, T Werge, D Hougaard, PB Mortensen, E Agerbo.*   
https://doi.org/10.1016/j.bbi.2020.07.030


**Linking the association between circRNAs and Alzheimer’s disease progression by multi-tissue circular RNA characterization.  **  
*I-J Lo, J Hill, BJ Vilhjálmsson, J Kjems.*   
https://doi.org/10.1080/15476286.2020.1783487


**Polygenic risk and progression to bipolar or psychotic disorders among individuals diagnosed with unipolar depression.  **   
*K Musliner, M Krebs, C Albiñana Climent, BJ Vilhjálmsson, E Agerbo, P Zandi, D Hougaard, M Nordentoft, A Børglum, T Werge, PB Mortensen, S Østergaard.*   
https://doi.org/10.1176/appi.ajp.2020.19111195


**Association Between Childhood Green Space, Genetic Liability, and the Incidence of Schizophrenia. **     
*K Engemann, J-C Svenning, E Agerbo, L Arge, A Børglum, A Dupont, C Erikstrup, O Hertel, D Hougaard, JJ McGrath, PB Mortensen, M Nordentoft, CE Sabel, T Sigsgaard, C Tsirogiannis, BJ Vilhjálmsson, T Werge, CB Pedersen, HT Horsdal.*   
https://doi.org/10.1093/schbul/sbaa058


**Association between Mental Disorders and Subsequent Medical Conditions.   **   
*NC Momen, O Plana-Ripoll, E Agerbo, ME Benros, A Børglum, MK Christensen, S Dalsgaard, L Degenhardt, P de Jonge, J-C Debost, M Fenger-Grøn, JM Gunn, KM Iburg, LV Kessing, RC Kessler, TM Laursen, C Lim, O Mors, PB Mortensen, K Musliner, M Nordentoft, CB Pedersen, LV Petersen, AR Ribe, AM Roest, S Saha, AJ Schork, KM Scott, HJ Sørensen, TJ Stedman, M Vestergaard, BJ Vilhjálmsson, T Werge, N Weye, HA Whiteford, A Prior, JJ McGrath.*   
https://doi.org/10.1056/nejmoa1915784


**Symbiosis genes show a unique pattern of introgression and selection within a Rhizobium leguminosarum species complex.**    
*MI Cavassim Alves, S Moeskjær, C Moslemi, B Fields, A Bachmann, BJ Vilhjálmsson, MH Schierup, JPW Young, SU Andersen.*   
https://doi.org/10.1099/mgen.0.000351


**JASS: Command Line and Web interface for the joint analysis of GWAS results. **     
*H Julienne, P Lechat, V Guillemot, C Lasry, C Yao, R Araud, V Laville, BJ Vilhjálmsson, H Menager, H Aschard.*   
https://doi.org/10.1093/nargab/lqaa003


**Extreme genetic signatures of local adaptation during Lotus japonicus colonization of Japan.**      
*N Shah, T Wakabayashi, Y Kawamura, C Skovbjerg, M-Z Wang, Y Mustamin, Y Isomura, V Gupta, H Jin, T Mun, N Sandal, F Azuma, E Fukai, Ü Seren, S Kusakabe, Y Kikuchi, S Nitanda, T Kumaki, M Hashiguchi, H Tanaka, A Hayashi, M Sønderkær, K Nielsen, K Schneeberger, BJ Vilhjálmsson, R Akashi, J Stougaard, S Sato, M Schierup, SU Andersen.*   
https://doi.org/10.1038/s41467-019-14213-y

   
## 2019

**Headaches and polygenic scores.   **   
*BJ Vilhjálmsson, F Privé.*   
https://ng.neurology.org/content/5/6/e368


**Making the Most of Clumping and Thresholding for Polygenic Scores. **     
*F Privé, BJ Vilhjálmsson, H Aschard, MG Blum.*   
https://doi.org/10.1016/j.ajhg.2019.11.001


**Association of Childhood Exposure to Nitrogen Dioxide and Polygenic Risk Score for Schizophrenia With the Risk of Developing Schizophrenia.   **   
*HT Horsdal, E Agerbo, JJ McGrath, BJ Vilhjálmsson, S Antonsen, AM Closter, A Timmermann, J Grove, P Mok, RT Webb, CE Sabel, O Hertel, T Sigsgaard, C Erikstrup, DM Hougaard, T Werge, M Nordentoft, A Børglum, O Mors, PB Mortensen, J Brandt, C Geels and CB Pedersen.*   
https://doi.org/10.1001/jamanetworkopen.2019.14401


**Association Mapping and Disease: Evolutionary Perspectives. **     
*S Besenbacher, T Mailund, BJ Vilhjálmsson, MH Schierup.*    
https://doi.org/10.1007/978-1-4939-9074-0_17


**Transgenerational effects of inter-ploidy cross direction on reproduction and seed development in Arabidopsis thaliana F1 hybrid triploids.   **   
*D Duszynska, BJ Vilhjálmsson, R Castillo Bravo, S Swamidatta, TE Younger, MTA Donoghue A Comte; M Nordborg, TF Sharbel, G Brychkova, PC McKeown; C Spillane.*   
https://doi.org/10.1007/s00497-019-00369-6


   
## 2018

**The nature of nurture: Effects of parental genotypes.   **      
*A Kong, G Thorleifsson, ML Frigg, BJ Vilhjálmsson, AI Young, TE Thorgeirsson, S Benonisdottir, A Oddsson, BV Halldorsson, G Masson, D Gudbjartsson, A Helgason, G Bjornsdottir, U Thorsteinsdottir, K Stefansson. *   
https://doi.org/10.1126/science.aan6877


**PhenoSpD: an atlas of phenotypic correlations and a multiple testing correction for the human phenome. **     
*J Zheng, T Richardson, L Millard, G Hemani, C Raistrick, BJ Vilhjálmsson, P Haycock, T Gaunt. *   
https://doi.org/10.1093/gigascience/giy090


   
## 2017

**Covariate selection for association screening in multi-phenotype genetic studies.  **    
*H Aschard, V Guillemot, BJ Vilhjálmsson, CJ Patel, D Skurnik, J Yu, B Wolpin, P Kraft, N Zaitlen. *   
https://doi.org/10.1038/ng.3975


   
## 2016

**Nationwide Genomic Study in Denmark Reveals Remarkable Population Homogeneity. **     
*G Athanasiadis, J Cheng, BJ Vilhjálmsson, FG Jørgensen, TD Als, S Le Hellard, T Espeseth, PF Sullivan, CM Hultman, PC Kjærgaard, MH Schierup, and T Mailund. *   
https://doi.org/10.1534/genetics.116.189241


**Response to Day et al.   **   
*H Aschard, BJ Vilhjálmsson, A Joshi, AL Price, P Kraft.*   
https://doi.org/10.1016/j.ajhg.2015.12.020


   
## 2015

**Modeling linkage disequilibrium increases accuracy of polygenic risk scores. **     
*BJ Vilhjálmsson, J Yang, H Finucane, A Gusev, S Lindström, S Ripke, G Genovese, P-R Loh, G Bhatia, R Do, M Pato, C Pato, T Hayeck, H-H Won, Schizophrenia Working Group of the PGC, the Discovery, Biology, and Risk of Inherited Variants in Breast Cancer (DRIVE) study, S Kathiresan, M Pato, C Pato, R Tamimi, E Stahl, N Zaitlen, B Pasaniuc, MH Schierup, P De Jager, N Patsopoulos, S McCarroll, M Daly, S Purcell, D Chasman, B Neale, M Goddard, P Visscher, P Kraft, N Patterson, AL Price.*   
https://doi.org/10.1016/j.ajhg.2015.09.001


**Adjusting for heritable covariates can bias effect estimates in genome-wide association studies. **      
*H Aschard, BJ Vilhjálmsson, A Joshi, AL Price, P Kraft.*   
https://doi.org/10.1016%2Fj.ajhg.2014.12.021


**Polygenic Risk Score, Parental Socioeconomic Status, Family History of Psychiatric Disorders and the Risk of Schizophrenia: A Danish Population-Based Study.   **   
*E Agerbo, PF Sullivan, BJ Vilhjálmsson, CB Pedersen, O Mors, AD Børglum, DM Hougaard, MV Hollegaard, S Meier, S Ripke, NR Wray, PB Mortensen.*    
https://doi.org/10.1001/jamapsychiatry.2015.0346


**DNA methylation variation in Arabidopsis has a genetic basis and shows evidence of local adaptation.  **    
*MJ Dubin, P Zhang, D Meng, M-S Remigereau, EJ Osborne, FP Casale, P Drewe, A Kahles, BJ Vilhjálmsson, J Jagoda, S Irez, V Voronin, Q Song, Q Long, G Rätsch, O Stegle, RM Clark, M Nordborg.*   
https://doi.org/10.7554/eLife.05255


**Mixed model with correction for case-control ascertainment increases association power.  **    
*T Hayeck, NA Zaitlen, P-R Loh, BJ Vilhjálmsson, S Pollack, A Gusev, J Yang, G-B Chen, ME Goddard, PM Visscher, N Patterson, AL Price.*    
https://doi.org/10.1016/j.ajhg.2015.03.004


**Efficient Bayesian mixed model analysis increases association power in large cohorts.  **    
*P-R Loh, G Tucker, BK Bulik-Sullivan, BJ Vilhjálmsson, HK Finucane, RM Salem, DI Chasman, PM Ridker, BM Neale, B Berger, N Patterson, AL Price.*   
http://dx.doi.org/10.1101/007799


   
## 2014

**Maximizing the Power in Genome-wide Association Studies of Principal Components from Correlated Phenotypes. **    
*H Aschard, BJ Vilhjálmsson, N Greliche, P-E Morange, D-A Trégouët, P Kraft.*   
https://doi.org/10.1016/j.ajhg.2014.03.016


**Leveraging population admixture to characterize the heritability of complex traits.   **   
*N Zaitlen, B Pasaniuc, S Sankararam, G Bhatia, J Zhang, A Gusev, T Young, A Tandon, S Pollack, BJ Vilhjálmsson, TL Assimes, SI Berndt, WJ Blot, S Chanock, N Franceschini, PG Goodman, J He, AJM Hennis, A Hsing, SA Ingles, W Isaacs, RA Kittles, EA Klein, LA Lange, B Nemesure, N Patterson, D Reich, BA Rybicki, JL Stanford, VL Stevens, SS Strom, EA Whitsel, JS Witte, J Xu, C Haiman, JG Wilson, C Kooperberg, D Stram, AP Reiner, H Tang, AL Price.*    
https://doi.org/10.1038/ng.3139


**Partitioning Heritability of Regulatory and Cell-Type-Specific Variants across 11 Common Diseases.   **   
*A Gusev, SH Lee, G Trynka, H Finucane, BJ Vilhjálmsson, H Xu, C Zang, S Ripke, B Bulik-Sullivan, E Stahl, Schizophrenia Working Group of the Psychiatric Genomics Consortium, SWE-SCZ Consortium, AK Kahler, CM Hultman, SM Purcell, SA McCarroll, M Daly, B Pasaniuc, PF Sullivan, B Neale, NR Wray, S Raychaudhuri, AL Price.*   
https://doi.org/10.1016/j.ajhg.2014.10.004


**Genome-wide association study of Arabidopsis thaliana leaf microbial community.  **    
*MW Horton, N Bodenhausen, K Beilsmith, D Meng, BD Muegge, S Subramanian, MM Vetter, BJ Vilhjálmsson, M Nordborg, JI Gordon, J Bergelson.*   
http://dx.doi.org/10.1038/ncomms6320


**Effect of genetic variation in a Drosophila model of diabetes-associated misfolded human proinsulin. **     
*BZ He, MZ Ludwig, DA Dickerson, L Barse, B Arun, BJ Vilhjálmsson, S-Y Park, NA Tamarina, SB Selleck, PJ Wittkopp, GI Bell, M Kreitman.*   
https://doi.org/10.1534/genetics.113.157800

   
## 2013

**The nature of confounding in genome-wide association studies. **     
*BJ Vilhjálmsson and M Nordborg.*   
https://doi.org/10.1038/nrg3382


**Quantifying missing heritability at known GWAS loci.   **   
*A Gusev, G Bhatia, N Zaitlen, BJ Vilhjálmsson, D Diogo, EA Stahl, PK Gregersen, JWorthington, L Klareskog, S Raychaudhuri, RM Plenge, B Pasaniuc, AL Price.*   
https://doi.org/10.1371/journal.pgen.1003993


**Massive genomic variation and strong selection in Arabidopsis thaliana lines from Sweden. **     
*Q Long, FA Rabanal, D Meng, CD Huber, A Farlow, A Platzer, Q Zhang, BJ Vilhjálmsson, A Korte, V Nizhynska, V Voronin, Ü Seren, L Sedman, I Hellmann, M Nordborg.*    
https://doi.org/10.1038/ng.2678


**Genetic architecture of skin and eye color in an African-European admixed population. **    
*S Beleza, NA Johnson, SI Candille, DM Absher, MA Coram, J Lopes, J Campos, II Araújo, TM Anderson, BJ Vilhjálmsson, M Nordborg, A Correia e Silva, MD Shriver, J Rocha, GS Barsh, H Tang.*   
https://doi.org/10.1371/journal.pgen.1003372


**JAWAMix5: an out-of-core HDF5-based java implementation of whole-genome association studies using mixed models.  **    
*Q Long, Q Zhang, BJ Vilhjálmsson, Ü Seren, P Forai, M Nordborg.*   
https://doi.org/10.1093/bioinformatics/btt122

   
## 2012

**Multilocus mixed model for genome-wide association studies in structured populations. **     
*V Segura, BJ Vilhjálmsson, A Platt, A Korte, Ü Seren, Q Long, and M Nordborg.*   
https://doi.org/10.1038%2Fng.2314


**A mixed model for genome-wide association studies of correlated traits in structured populations. **     
*A Korte, BJ Vilhjálmsson, V Segura, A Platt, Q Long, and M Nordborg.*   
https://doi.org/10.1038/ng.2376


**GWAPP: A web application for genome-wide association studies in A. thaliana.**      
*Ü Seren, BJ Vilhjálmsson, MW Horton, D Meng, P Forai, YS Huang, Q Long, V Segura, and M Nordborg.*   
https://doi.org/10.1105/tpc.112.108068


**Genome-wide patterns of genetic variation in worldwide Arabidopsis thaliana accessions from the RegMap panel.**      
*MW Horton, AM Hancock, YS Huang, C Toomajian, S Atwell, A Auton, NW Muliyati, A Platt, FG Sperone, BJ Vilhjálmsson, M Nordborg, JO Borevitz, J Bergelson.*   
https://doi.org/10.1038%2Fng.1042


   
## 2011

**Analysis and visualization of Arabidopsis thaliana GWAS using web 2.0 technologies.**      
*YS Huang, M Horton, BJ Vilhjálmsson, Ü Seren, D Meng, C Meyer, MA Amer, JO Borevitz, J Bergelson, and M Nordborg.*   
https://doi.org/10.1093/database/bar014

   
## 2010

**Genome-wide association study of 107 phenotypes in Arabidopsis thaliana inbred lines.**      
*S Atwell, YS Huang, BJ Vilhjálmsson, G Willems, M Horton, Y Li, D Meng, A Platt, AM Tarone, TT Hu, R Jiang, NW Muliyati, X Zhang, MA Amer, I Baxter, B Brachi, J Chory, C Dean, M Debieu, J De Meaux, JR Ecker, N Faure, JM Kniskern, JDG Jones, T Michael, A Nemri, F Roux, DE Salt, C Tang, M Todesco, MB Traw, D Weigel, P Marjoram, JO Borevitz, J Bergelson, M Nordborg.*   
https://doi.org/10.1038/nature08800


**Conditions Under Which Genome-wide Association Studies Will be Positively Misleading.**      
*A Platt, BJ Vilhjálmsson, M Nordborg.*   
https://doi.org/10.1534/genetics.110.121665

